version: '3.8'
services:

  db-provider:
    image: "postgres"
    restart: always
    environment:
      POSTGRES_PASSWORD: ds_transfer_provider
      POSTGRES_USER: ds_transfer_provider
      POSTGRES_DB: ds_transfer_provider


  ds-provider:
    image: caparicioesd/rainbow:0.2
    platform: linux/amd64
    restart: on-failure
    depends_on:
      - db-provider
    ports:
      - "1200:1200"
    env_file:
      - "./.env.core.provider.template"
    command: [ "provider", "start" ]


  ds-provider-setup:
    image: caparicioesd/rainbow:0.2
    platform:  linux/amd64
    restart: on-failure
    depends_on:
      - db-provider
    env_file:
      - "./.env.core.provider.template"
    command: [ "provider", "setup" ]


  db-consumer:
    image: "postgres"
    restart: always
    environment:
      POSTGRES_PASSWORD: ds_core_consumer_db
      POSTGRES_USER: ds_core_consumer_db
      POSTGRES_DB: ds_core_consumer_db


  ds-consumer:
    image: caparicioesd/rainbow:0.2
    platform:  linux/amd64
    restart: on-failure
    depends_on:
      - db-consumer
    ports:
      - "1100:1100"
    env_file:
      - "./.env.core.consumer.template"
    command: [ "consumer", "start" ]


  ds-consumer-setup:
    image: caparicioesd/rainbow:0.2
    platform:  linux/amd64
    restart: on-failure
    depends_on:
      - db-consumer
    env_file:
      - "./.env.core.consumer.template"
    command: [ "consumer", "setup" ]


